languageCode = "it"
languageName = "Italiano"
weight = 2
title = "Terraforming the Cloud"

[params]
  displayName = "IT"
  isoCode = "it"
  rtl = false
  logo = "img/logo.png"
  dateFormat = "2 January 2006"
  description = "Il mio blog personale su self-hosting e tecnologia."

[params.author]
  name = "Roberto Tazzoli"
  image = "img/profile.jpg"
  headline = "Homelab Platform Engineer & Appassionato di Kubernetes"
  bio = "Appassionato di infrastrutture dichiarative, self-hosting e Kubernetes."
  links = [
    { github = "https://github.com/tazzo" }
  ]