languageCode = "en"
languageName = "English"
weight = 1
title = "Terraforming the Cloud"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "My personal blog about self-hosting and technology."

[params.author]
  name = "Roberto Tazzoli"
  image = "img/profile.jpg"
  headline = "Platform Engineer & Kubernetes Enthusiast"
  bio = "Passionate about declarative infrastructure, self-hosting, and Kubernetes."
  links = [
    { github = "https://github.com/tazzo" }
  ]